const randomName = ["Arjun", "Rohan", "Vikram", "Aditya", "Siddharth", "Rajesh", "Amit", "Karan", "Manoj", "Naveen", 
"Prakash", "Suresh", "Ravi", "Ankit", "Deepak", "Harish", "Vivek", "Sunil", "Gaurav", "Rahul", 
"Neha", "Pooja", "Aarti", "Shreya", "Sneha", "Priya", "Divya", "Meera", "Kavita", "Anjali", 
"Nisha", "Swati", "Rekha", "Payal", "Sonia", "Simran", "Ritu", "Isha", "Kiran", "Alka", 
"Arnav", "Ishaan", "Kabir", "Rudra", "Yash", "Dev", "Lakshya", "Om", "Parth", "Kunal", 
"Aryan", "Tanmay", "Samar", "Viraj", "Tejas", "Abhay", "Shivansh", "Chirag", "Mohan", "Krishna", 
"Lavanya", "Tanvi", "Muskan", "Juhi", "Radha", "Sakshi", "Bhavna", "Vidya", "Roshni", "Trisha"
]
const randomMessage = ["Arre bhai tu offline tha ya Himalaya chadh gaya tha? 🏔️😂",
"Yaar tera hairstyle dekh ke wifi signal yaad aaya 📶🤣",
"Tu gym jata hai ya sirf insta pe check-in karta hai? 💪📸😆",
"Abe tu khud ki DP pe khud hi like karta hai kya? 🤔😂",
"Chai pee ya chai ne tujhe piya? ☕😜",
"Tera joke sun ke mera WiFi bhi hang ho gaya 🤯🤣",
"Tu padhai karta hai ya Google se dosti nibha raha hai? 📚🤖😂",
"Abe ye filter lagaya hai ya asli mein alien hai tu? 👽🤣",
"Whatsapp last seen off kar ke kya RAW agent ban gaya hai? 🕵️‍♂️😂",
"Tu selfie leta hai ya selfie tujhe leti hai? 🤳😆",
"Jyada smart mat ban, tera password bhi '1234' hoga 😜🔑",
"Abe tu real life mein bhi typing... typing... karta hai kya? ⌨️😂",
"Tu exam mein pass hoga ya examiner ko bhi confuse karega? 📝🤔🤣",
"Tere jokes sun ke Siri bhi chup ho gayi 😂📱",
"Tu Google map hai kya? Sabko ghoomata rehta hai 🗺️🤣",
"Tu khud ko hero samajhta hai ya flipkart ke free return item hai? 📦😂",
"Teri speed dekh ke BSNL bhi khush ho gaya 🐢🤣",
"Abe tu English bolta hai ya autocorrect? 🔤😂",
"Tu khud ko rich samajhta hai par recharge bhi dusre se karwata hai? 💸😂",
"Tu pyaar karta hai ya only 'seen' deta hai? 💔👀🤣",
"Tu itna funny hai ki mirror bhi hans padta hai 😂🪞",
"Status dalta hai ya poetry competition jeetna hai? ✍️🤣",
"Tu selfie mein smile karta hai ya teeth ka ad shoot karta hai? 😬📸",
"Tu real hai ya Reels ka side effect? 🎥🤣",
"Abe tu khud hi apna fan hai kya? 🪭😂",
"Tu khud ko Salman samajhta hai, par reality mein Govinda bhi nahi 😜🎬",
"Teri speed se toh Windows XP bhi fast hai 💻🐌😂",
"Tu khud ko hacker samajhta hai aur Gmail ka password bhi bhool gaya? 🔐🤣",
"Tu asli hai ya duplicate TikTok ka version? 📱😂",
"Tu khud ko influencer bolta hai, par follower teri mummy hi hai 🤣👩",
"Abe tu sochta hai ya loading chal raha hai? 🔄😂",
"Tere hairstyle mein network tower lag raha hai 📡🤣",
"Tu khud ko PUBG ka pro samajhta hai aur reload karna bhi bhool jata hai 🎮😂",
"Tu exam mein answer likhta hai ya essay ka trailer? 📖🤣",
"Tu selfie dalta hai ya aadhaar update karwa raha hai? 🆔😂",
"Abe tu dance karta hai ya washing machine spin mode? 🕺🌀🤣",
"Tu khud ko Ronaldo samajhta hai aur football dekhna bhi mushkil hai ⚽😂",
"Tu khud hi apna fan club banata hai kya? 😆👬",
"Teri aankhon mein stars hain ya phone ka torch on hai? ✨🔦😂",
"Tu padhai karta hai ya syllabus ka funeral plan? 📚⚰️🤣",
"Tu ladki impress karta hai ya comedy circus audition? 🤡🤣",
"Tu khud ko engineer bolta hai aur bulb tak nahi badal sakta 💡😂",
"Tu sochta hai ya buffering chal raha hai? ⏳😂",
"Tu khud ko singer bolta hai, par bathroom bhi protest karta hai 🚿🎤🤣",
"Tera handwriting dekh ke doctor bhi confuse ho jaye 📝😂",
"Abe tu Whatsapp pe online hai ya permanent resident hai? 🟢😂",
"Tu khud ko king bolta hai aur chess bhi nahi aata 👑♟️🤣",
"Tu khud ko gamer bolta hai aur ludo mein hi haar jata hai 🎲😂",
"Tu khud ko chef samajhta hai aur Maggie bhi 20 min mein banata hai 🍜🤣",
"Tere speed se toh snail bhi overtake kar le 🐌🏎️😂",
"Tu khud ko fashion icon bolta hai, par kapde mismatched hote hain 👕👖😂",
"Tu khud ko poet bolta hai aur rhyme bhi nahi banta ✍️🤣",
"Tu khud ko strong bolta hai aur bottle kholne mein help mangta hai 🍼😂",
"Tu khud ko romantic bolta hai aur flowers bhi plastic ke deta hai 🌸🤣",
"Tu khud ko leader bolta hai aur line mein last khada rehta hai 🚶‍♂️😂",
"Tu khud ko scientist bolta hai aur vinegar aur soda bhi confuse karta hai 🧪😂",
"Tere confidence dekh ke wifi bhi connect nahi hota 📶🤣",
"Tu khud ko dancer bolta hai aur step dekh ke Alexa bhi mute ho gayi 🤖😂",
"Tu khud ko serious bolta hai aur meme bhi forward karta hai 🤳🤣",
"Tu khud ko genius bolta hai aur spelling mein 'genius' galat likhta hai 🔠😂",
"Tu khud ko fast bolta hai aur lift ka wait karta hai ⏫😂",
"Tu khud ko stylist bolta hai aur socks alag color ki pehnta hai 🧦🤣",
"Teri DP dekh ke lagta hai passport reject ho jayega 📸😂",
"Tu khud ko rich bolta hai aur free WiFi dhundta rehta hai 📶😂",
"Tu khud ko cool bolta hai aur AC ke neeche baith ke selfie dalta hai ❄️🤣",
"Tu khud ko star bolta hai aur khud hi comments karta hai ⭐😂",
"Tu khud ko foodie bolta hai aur discount coupon dhundta hai 🍔😂",
"Tu khud ko legend bolta hai aur spelling 'lagend' likhta hai 🤣✍️",
"Tere jokes sun ke Google bhi suggestion band kar de 😂🔍",
"Tu khud ko pro bolta hai aur video call mein camera band hota hai 📹🤣",
"Tu khud ko bodybuilder bolta hai aur dumbbell uthate hi dum nikal jata hai 🏋️‍♂️😂",
"Tu khud ko rich bolta hai aur Paytm pending hota hai 💸🤣",
"Tu khud ko serious bolta hai aur khud pe hi laugh react karta hai 😆😂",]

export const generateRandomName = () =>{
    return randomName[Math.floor(Math.random() * randomName.length)]
}
export const generateRandomMessage = () =>{
    return randomMessage[Math.floor(Math.random() * randomMessage.length)]
}